name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  unit-and-integration:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run unit and integration tests
        run: ./mvnw clean verify

  sonar:
    name: Unit, Integration & SonarCloud
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run tests, generate coverage and analyze with Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.hc.client5.http.wire=ERROR"
        run: |
          ./mvnw clean verify sonar:sonar \
            "-Dsonar.projectKey=BielPimentaDev_waiterapp" \
            "-Dsonar.organization=bielpimentadev" \
            "-Dsonar.host.url=https://sonarcloud.io" \
            "-Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml" \
            "-Dmaven.test.failure.ignore=true"
